#!/usr/bin/env python3
"""Maintain the main-manager project registry and validate project summaries."""
from __future__ import annotations

import argparse
import fcntl
import os
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

DEFAULT_ROOT = Path(os.environ.get("OMO_WORK_LOGS_ROOT", Path.home() / "work_logs"))
DEFAULT_REGISTRY = Path("manager_projects.md")
FIELD_RE = re.compile(r"^- ([a-z0-9-]+):\s*(.*)$")
SECTION_RE = re.compile(r"(?ms)^## (?P<project_id>[A-Za-z0-9._-]+)\n(?P<body>.*?)(?=^## |\Z)")
SAFE_PROJECT_ID_RE = re.compile(r"^[A-Za-z0-9._-]{1,80}$")
REGISTRY_FIELDS = ("name", "status", "submanager-target", "submanager-task", "summary-file", "goal", "blocker", "last-heartbeat", "next-checkpoint")
SUMMARY_FIELDS = ("project", "status", "owner", "goal", "state", "next-action", "blocker", "risk", "last-heartbeat", "next-checkpoint", "evidence")


@dataclass(frozen=True)
class Args:
    root: Path
    registry: Path
    command: str
    project_id: str
    values: dict[str, str]
    summary_file: Path | None


def resolve_under_root(root: Path, path: Path) -> Path:
    resolved_root = root.resolve()
    resolved = path.resolve() if path.is_absolute() else (resolved_root / path).resolve()
    try:
        _ = resolved.relative_to(resolved_root)
    except ValueError as exc:
        raise ValueError(f"path must stay under root: {path}") from exc
    return resolved


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, raw_tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    tmp = Path(raw_tmp)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        tmp.replace(path)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise


def registry_header() -> str:
    return """# manager project registry

Main-manager-owned durable registry. Project submanagers report compact summaries here through their `summary-file`; they do not edit this file directly.

"""


def parse_fields(body: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for line in body.splitlines():
        match = FIELD_RE.match(line)
        if match is not None:
            fields[match.group(1)] = match.group(2).strip()
    return fields


def parse_sections(text: str) -> dict[str, dict[str, str]]:
    return {match.group("project_id"): parse_fields(match.group("body")) for match in SECTION_RE.finditer(text)}


def format_section(project_id: str, values: dict[str, str]) -> str:
    lines = [f"## {project_id}"]
    for field in REGISTRY_FIELDS:
        value = values.get(field, "")
        lines.append(f"- {field}: {value}")
    return "\n".join(lines) + "\n"


def format_registry(projects: dict[str, dict[str, str]]) -> str:
    lines = [registry_header().rstrip(), ""]
    for project_id in sorted(projects):
        lines.append(format_section(project_id, projects[project_id]).rstrip())
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def upsert_project(path: Path, project_id: str, values: dict[str, str]) -> None:
    if SAFE_PROJECT_ID_RE.fullmatch(project_id) is None:
        raise ValueError(f"unsafe project id: {project_id}")
    lock_path = path.with_suffix(path.suffix + ".lock")
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with lock_path.open("w", encoding="utf-8") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        projects = parse_sections(read_text(path))
        merged = {field: "" for field in REGISTRY_FIELDS}
        merged.update(projects.get(project_id, {}))
        merged.update({key: value for key, value in values.items() if value != ""})
        projects[project_id] = merged
        atomic_write(path, format_registry(projects))


def validate_registry(path: Path, root: Path) -> list[str]:
    text = read_text(path)
    if not text.strip():
        return [f"missing registry: {path}"]
    projects = parse_sections(text)
    if not projects:
        return [f"registry has no projects: {path}"]
    problems: list[str] = []
    for project_id, fields in projects.items():
        missing = [field for field in REGISTRY_FIELDS if not fields.get(field)]
        if missing:
            problems.append(f"{project_id}: missing registry fields: {', '.join(missing)}")
        summary = fields.get("summary-file", "")
        if summary:
            summary_path = resolve_under_root(root, Path(summary))
            problems.extend(validate_summary(summary_path, project_id, fields.get("submanager-target", "")))
        submanager_task = fields.get("submanager-task", "")
        if submanager_task and not resolve_under_root(root, Path(submanager_task)).is_file():
            problems.append(f"{project_id}: missing submanager task: {submanager_task}")
    return problems


def validate_summary(path: Path, project_id: str, expected_owner: str = "") -> list[str]:
    text = read_text(path)
    if not text.strip():
        return [f"{project_id}: missing summary file: {path}"]
    fields = parse_fields(text)
    missing = [field for field in SUMMARY_FIELDS if not fields.get(field)]
    problems = [f"{project_id}: missing summary fields in {path.name}: {', '.join(missing)}"] if missing else []
    if project_id and fields.get("project") and fields["project"] != project_id:
        problems.append(f"{project_id}: summary project field is {fields['project']}")
    if expected_owner and fields.get("owner") and fields["owner"] != expected_owner:
        problems.append(f"{project_id}: summary owner {fields['owner']} does not match registry submanager-target {expected_owner}")
    return problems


def nonempty_arg(value: str | None) -> str:
    return "" if value is None else " ".join(value.split())


def parse_args(argv: list[str]) -> Args:
    parser = argparse.ArgumentParser(description=__doc__)
    _ = parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    _ = parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    sub = parser.add_subparsers(dest="command", required=True)
    _ = sub.add_parser("init")
    upsert = sub.add_parser("upsert")
    _ = upsert.add_argument("--project-id", required=True)
    for field in REGISTRY_FIELDS:
        _ = upsert.add_argument(f"--{field}", default="")
    check = sub.add_parser("check")
    _ = check.add_argument("--summary-file", type=Path)
    _ = check.add_argument("--project-id", default="")
    parsed = parser.parse_args(argv)
    values = {field: nonempty_arg(getattr(parsed, field.replace("-", "_"), "")) for field in REGISTRY_FIELDS} if parsed.command == "upsert" else {}
    return Args(parsed.root.resolve(), resolve_under_root(parsed.root.resolve(), parsed.registry), parsed.command, getattr(parsed, "project_id", ""), values, getattr(parsed, "summary_file", None))


def main(argv: list[str] | None = None) -> int:
    try:
        args = parse_args(sys.argv[1:] if argv is None else argv)
        if args.command == "init":
            if not args.registry.exists():
                atomic_write(args.registry, registry_header())
            print(f"registry: {args.registry}")
            return 0
        if args.command == "upsert":
            upsert_project(args.registry, args.project_id, args.values)
            print(f"project-upserted: {args.project_id}")
            return 0
        if args.command == "check":
            problems = validate_summary(resolve_under_root(args.root, args.summary_file), args.project_id) if args.summary_file is not None else validate_registry(args.registry, args.root)
            if problems:
                print("project-registry: fail")
                print("\n".join(problems))
                return 1
            print("project-registry: ok")
            return 0
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    raise AssertionError(args.command)


if __name__ == "__main__":
    raise SystemExit(main())
